[theme]
base                = "dark"
backgroundColor     = "#0D1B2A"
secondaryBackgroundColor = "#112240"
textColor           = "#CCD6F6"
primaryColor        = "#1DB954"
font                = "sans serif"
